apiVersion: 1

datasources:
  - name: Gigapipe
    type: loki
    access: proxy
    # Gigapipe expose Loki-compatible API di port 3100
    url: http://gigapipe:3100
    isDefault: true
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
