---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb-sa
  namespace: monitoring
imagePullSecrets:
  - name: regcred

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: influxdb-sa
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

---
apiVersion: v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influxdb-sa
rules:
  - apiGroups:     ['policy']
    resources:     ['podsecuritypolicies']
    verbs:         ['use']
    resourceNames: ['influxdb-sa']
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: influxdb-sa
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: influxdb-sa
subjects:
  - kind: ServiceAccount
    name: influxdb-sa
    namespace: monitoring

---
apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influxdb-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: influxdb-sa
subjects:
- kind: ServiceAccount
  name: influxdb-sa
  namespace: monitoring

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  namespace: monitoring
type: Opaque
stringData:
  # USERNAME : influxdb
  DOCKER_INFLUXDB_INIT_USERNAME: influxdb
  # PASSWORD : 4oGwN9aJo0rL
  DOCKER_INFLUXDB_INIT_PASSWORD: 4oGwN9aJo0rL
  # TOKEN : SYxE3hPS2pSHPY59T8Ox65qJ3J1EvrXcdK0WfUKCCZ5PFKkmIZmZLehekKQY4IzP
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: SYxE3hPS2pSHPY59T8Ox65qJ3J1EvrXcdK0WfUKCCZ5PFKkmIZmZLehekKQY4IzP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: influxdb-sa
      containers:
        - name: influxdb
          image: influxdb:2.7
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: monitoring
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: nginx
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_USERNAME
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086