---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  namespace: monitoring
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: kuceng
  DOCKER_INFLUXDB_INIT_PASSWORD: belagak12345
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: supersecrettoken

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: monitoring
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: nginx
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_USERNAME
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086