---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: api-management
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encode>