[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000

[global_tags]
  service = "nginx"
  env = "dev"
  instance = "nginx-1"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "supersecrettoken"
  organization = "monitoring"
  bucket = "nginx"

# === NGINX stub_status ===
[[inputs.nginx]]
  urls = ["http://nginx/nginx_status"]

# === Parse NGINX access log ===
[[inputs.tail]]
  files = ["/var/log/nginx/access.log"]
  from_beginning = true
  name_override = "nginx_access"
  data_format = "grok"
  #grok_patterns = ["%{IP:client_ip} %{NUMBER:status:int} %{NUMBER:request_time:float} \"%{WORD:method} %{DATA:uri} HTTP/%{NUMBER:http_version}\" \"%{DATA:country_code:tag}\" \"%{DATA:country_name:tag}\" \"%{DATA:city_name:tag}\" %{DATA:latitude} %{DATA:longitude}"]
  grok_patterns = ["%{IP:client_ip} %{NUMBER:status:int} %{NUMBER:request_time:float} \"%{WORD:method} %{DATA:uri} HTTP/%{NUMBER:http_version}\" \"%{DATA:country_code:tag}\" \"%{DATA:country_name:tag}\" \"%{DATA:city_name:tag}\" %{NUMBER:latitude:float} %{NUMBER:longitude:float}"]


[[outputs.file]]
  files = ["stdout"]